package com.bank.pojo;

import java.io.Serializable;
import java.util.Date;

public class Brrow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.brrowid
     *
     * @mbggenerated
     */
    private Integer brrowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.bookid
     *
     * @mbggenerated
     */
    private Integer bookid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.readerid
     *
     * @mbggenerated
     */
    private Integer readerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.brrowdate
     *
     * @mbggenerated
     */
    private Date brrowdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.backdate
     *
     * @mbggenerated
     */
    private Date backdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brrowtable.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table brrowtable
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.brrowid
     *
     * @return the value of brrowtable.brrowid
     *
     * @mbggenerated
     */
    public Integer getBrrowid() {
        return brrowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.brrowid
     *
     * @param brrowid the value for brrowtable.brrowid
     *
     * @mbggenerated
     */
    public void setBrrowid(Integer brrowid) {
        this.brrowid = brrowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.bookid
     *
     * @return the value of brrowtable.bookid
     *
     * @mbggenerated
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.bookid
     *
     * @param bookid the value for brrowtable.bookid
     *
     * @mbggenerated
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.readerid
     *
     * @return the value of brrowtable.readerid
     *
     * @mbggenerated
     */
    public Integer getReaderid() {
        return readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.readerid
     *
     * @param readerid the value for brrowtable.readerid
     *
     * @mbggenerated
     */
    public void setReaderid(Integer readerid) {
        this.readerid = readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.brrowdate
     *
     * @return the value of brrowtable.brrowdate
     *
     * @mbggenerated
     */
    public Date getBrrowdate() {
        return brrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.brrowdate
     *
     * @param brrowdate the value for brrowtable.brrowdate
     *
     * @mbggenerated
     */
    public void setBrrowdate(Date brrowdate) {
        this.brrowdate = brrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.backdate
     *
     * @return the value of brrowtable.backdate
     *
     * @mbggenerated
     */
    public Date getBackdate() {
        return backdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.backdate
     *
     * @param backdate the value for brrowtable.backdate
     *
     * @mbggenerated
     */
    public void setBackdate(Date backdate) {
        this.backdate = backdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brrowtable.note
     *
     * @return the value of brrowtable.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brrowtable.note
     *
     * @param note the value for brrowtable.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brrowtable
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Brrow other = (Brrow) that;
        return (this.getBrrowid() == null ? other.getBrrowid() == null : this.getBrrowid().equals(other.getBrrowid()))
            && (this.getBookid() == null ? other.getBookid() == null : this.getBookid().equals(other.getBookid()))
            && (this.getReaderid() == null ? other.getReaderid() == null : this.getReaderid().equals(other.getReaderid()))
            && (this.getBrrowdate() == null ? other.getBrrowdate() == null : this.getBrrowdate().equals(other.getBrrowdate()))
            && (this.getBackdate() == null ? other.getBackdate() == null : this.getBackdate().equals(other.getBackdate()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brrowtable
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBrrowid() == null) ? 0 : getBrrowid().hashCode());
        result = prime * result + ((getBookid() == null) ? 0 : getBookid().hashCode());
        result = prime * result + ((getReaderid() == null) ? 0 : getReaderid().hashCode());
        result = prime * result + ((getBrrowdate() == null) ? 0 : getBrrowdate().hashCode());
        result = prime * result + ((getBackdate() == null) ? 0 : getBackdate().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brrowtable
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", brrowid=").append(brrowid);
        sb.append(", bookid=").append(bookid);
        sb.append(", readerid=").append(readerid);
        sb.append(", brrowdate=").append(brrowdate);
        sb.append(", backdate=").append(backdate);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}