package com.bank.pojo;

import java.io.Serializable;

public class Maer implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.workid
     *
     * @mbggenerated
     */
    private Integer workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.mname
     *
     * @mbggenerated
     */
    private String mname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.msex
     *
     * @mbggenerated
     */
    private String msex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mtable.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mtable
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.workid
     *
     * @return the value of mtable.workid
     *
     * @mbggenerated
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.workid
     *
     * @param workid the value for mtable.workid
     *
     * @mbggenerated
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.mname
     *
     * @return the value of mtable.mname
     *
     * @mbggenerated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.mname
     *
     * @param mname the value for mtable.mname
     *
     * @mbggenerated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.msex
     *
     * @return the value of mtable.msex
     *
     * @mbggenerated
     */
    public String getMsex() {
        return msex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.msex
     *
     * @param msex the value for mtable.msex
     *
     * @mbggenerated
     */
    public void setMsex(String msex) {
        this.msex = msex == null ? null : msex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.tel
     *
     * @return the value of mtable.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.tel
     *
     * @param tel the value for mtable.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.address
     *
     * @return the value of mtable.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.address
     *
     * @param address the value for mtable.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mtable.note
     *
     * @return the value of mtable.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mtable.note
     *
     * @param note the value for mtable.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtable
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Maer other = (Maer) that;
        return (this.getWorkid() == null ? other.getWorkid() == null : this.getWorkid().equals(other.getWorkid()))
            && (this.getMname() == null ? other.getMname() == null : this.getMname().equals(other.getMname()))
            && (this.getMsex() == null ? other.getMsex() == null : this.getMsex().equals(other.getMsex()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtable
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWorkid() == null) ? 0 : getWorkid().hashCode());
        result = prime * result + ((getMname() == null) ? 0 : getMname().hashCode());
        result = prime * result + ((getMsex() == null) ? 0 : getMsex().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mtable
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workid=").append(workid);
        sb.append(", mname=").append(mname);
        sb.append(", msex=").append(msex);
        sb.append(", tel=").append(tel);
        sb.append(", address=").append(address);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}