package com.bank.pojo;

import java.io.Serializable;
import java.util.Date;

public class Reader implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.readerid
     *
     * @mbggenerated
     */
    private Integer readerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.readername
     *
     * @mbggenerated
     */
    private String readername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.readersex
     *
     * @mbggenerated
     */
    private String readersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.effecttime
     *
     * @mbggenerated
     */
    private Date effecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.ineffecttime
     *
     * @mbggenerated
     */
    private Date ineffecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.booknum
     *
     * @mbggenerated
     */
    private Integer booknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column readertable.note
     *
     * @mbggenerated
     */
    private String note;

    private String password;

    private String identy;
    private Integer flowernum;
    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getFlowernum() {
        return flowernum;
    }

    public void setFlowernum(Integer flowernum) {
        this.flowernum = flowernum;
    }

    public String getIdenty() {
        return identy;
    }

    public void setIdenty(String identy) {
        this.identy = identy;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table readertable
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.readerid
     *
     * @return the value of readertable.readerid
     *
     * @mbggenerated
     */
    public Integer getReaderid() {
        return readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.readerid
     *
     * @param readerid the value for readertable.readerid
     *
     * @mbggenerated
     */
    public void setReaderid(Integer readerid) {
        this.readerid = readerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.readername
     *
     * @return the value of readertable.readername
     *
     * @mbggenerated
     */
    public String getReadername() {
        return readername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.readername
     *
     * @param readername the value for readertable.readername
     *
     * @mbggenerated
     */
    public void setReadername(String readername) {
        this.readername = readername == null ? null : readername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.readersex
     *
     * @return the value of readertable.readersex
     *
     * @mbggenerated
     */
    public String getReadersex() {
        return readersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.readersex
     *
     * @param readersex the value for readertable.readersex
     *
     * @mbggenerated
     */
    public void setReadersex(String readersex) {
        this.readersex = readersex == null ? null : readersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.tel
     *
     * @return the value of readertable.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.tel
     *
     * @param tel the value for readertable.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.effecttime
     *
     * @return the value of readertable.effecttime
     *
     * @mbggenerated
     */
    public Date getEffecttime() {
        return effecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.effecttime
     *
     * @param effecttime the value for readertable.effecttime
     *
     * @mbggenerated
     */
    public void setEffecttime(Date effecttime) {
        this.effecttime = effecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.ineffecttime
     *
     * @return the value of readertable.ineffecttime
     *
     * @mbggenerated
     */
    public Date getIneffecttime() {
        return ineffecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.ineffecttime
     *
     * @param ineffecttime the value for readertable.ineffecttime
     *
     * @mbggenerated
     */
    public void setIneffecttime(Date ineffecttime) {
        this.ineffecttime = ineffecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.booknum
     *
     * @return the value of readertable.booknum
     *
     * @mbggenerated
     */
    public Integer getBooknum() {
        return booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.booknum
     *
     * @param booknum the value for readertable.booknum
     *
     * @mbggenerated
     */
    public void setBooknum(Integer booknum) {
        this.booknum = booknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column readertable.note
     *
     * @return the value of readertable.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column readertable.note
     *
     * @param note the value for readertable.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readertable
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reader other = (Reader) that;
        return (this.getReaderid() == null ? other.getReaderid() == null : this.getReaderid().equals(other.getReaderid()))
            && (this.getReadername() == null ? other.getReadername() == null : this.getReadername().equals(other.getReadername()))
            && (this.getReadersex() == null ? other.getReadersex() == null : this.getReadersex().equals(other.getReadersex()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getEffecttime() == null ? other.getEffecttime() == null : this.getEffecttime().equals(other.getEffecttime()))
            && (this.getIneffecttime() == null ? other.getIneffecttime() == null : this.getIneffecttime().equals(other.getIneffecttime()))
            && (this.getBooknum() == null ? other.getBooknum() == null : this.getBooknum().equals(other.getBooknum()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readertable
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getReaderid() == null) ? 0 : getReaderid().hashCode());
        result = prime * result + ((getReadername() == null) ? 0 : getReadername().hashCode());
        result = prime * result + ((getReadersex() == null) ? 0 : getReadersex().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getEffecttime() == null) ? 0 : getEffecttime().hashCode());
        result = prime * result + ((getIneffecttime() == null) ? 0 : getIneffecttime().hashCode());
        result = prime * result + ((getBooknum() == null) ? 0 : getBooknum().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table readertable
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", readerid=").append(readerid);
        sb.append(", readername=").append(readername);
        sb.append(", readersex=").append(readersex);
        sb.append(", tel=").append(tel);
        sb.append(", effecttime=").append(effecttime);
        sb.append(", ineffecttime=").append(ineffecttime);
        sb.append(", booknum=").append(booknum);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}